matrix:
  include:

    # Training Data Project
    - language: java
      jdk:
        - oraclejdk8
        - openjdk8
      before_script:
        - cd data/java
        - mvn compile
      script:
        - mvn test

    # C++ Client
    - language: cpp
      compiler:
        - clang
        - gcc
      before_script:
        - cd data/cpp
        - cmake CMakeLists.txt
      script:
        - make
        - make test

    # Java Client
    - language: java
      jdk:
        - oraclejdk7  # minimum supported version
        - oraclejdk8
        - oraclejdk9
        - openjdk8
      before_script:
        - cd clients/java
      script:
        - mvn compile
        - mvn test

    # JavaScript Client
    - language: node_js
      node_js:
        - "node"
        - "0.10"  # minimum supported version
      before_script:
        - cd clients/js
        - npm install
      script:
        - npm run test

    # Ruby Client
    - language: ruby
      rvm:
        - 2.2
        - jruby
        - "2.0.0-p0"  # minimum supported version
      before_script:
        - cd clients/ruby
        - gem install bundler
        - bundle install
      script:
        - rake test
